// Package agents: State-Grounded Mock-Based In-Isolation Validation (NEW-PRIM-08 / TRAM [P10] §3).
//
// For each module under translation, MockValidator generates a state-equivalent
// stub for every listed dependency (interface signature only, no behaviour),
// re-executes the module against the stubs in an isolated directory using the
// project test runner from internal/tools/exec.go, and records per-stub
// assertion results that aggregate to a single Pass/Fail decision. This guards
// against translating a module that is silently coupled to its dependencies
// beyond what its surface signatures reveal.
package agents

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"MAgHARCM/internal/consts"
	"MAgHARCM/internal/logger"
	"MAgHARCM/internal/tools"
)

// IsolationReport captures the per-stub outcome of a single in-isolation run.
// Passed is true ONLY when every stub's assertion evaluated cleanly AND the
// module test run against the stubs returned no failures. Errors holds the
// human-readable detail for any stub that failed or any toolchain error.
type IsolationReport struct {
	Module           string   `json:"module"`
	MocksGenerated   []string `json:"mocks_generated"`
	StateAssertions  []string `json:"state_assertions"`
	Passed           bool     `json:"passed"`
	Errors           []string `json:"errors"`
}

// MockValidator runs State-Grounded Mock-Based In-Isolation Validation. A
// validator is configured with the language / toolchain of the module under
// translation (defaults to consts.LangRust / consts.ToolchainCargo when zero)
// and the project directory in which the module lives. The ProjectDir is the
// source tree; isolation runs happen in a per-call temp directory created by
// ValidateInIsolation so parallel validations cannot pollute one another.
type MockValidator struct {
	// Language identifies the project toolchain (e.g. consts.LangRust).
	// Empty means "auto-detect" via tools.RunProjectTests.
	Language string
	// Toolchain overrides the project toolchain (e.g. consts.ToolchainCargo).
	Toolchain string
	// ProjectDir is the source tree containing the module under validation.
	// Used as the directory passed to tools.RunProjectTests.
	ProjectDir string
}

// NewMockValidator constructs a MockValidator with the supplied language and
// toolchain. An empty ProjectDir is fine — callers may set it later or rely on
// the per-call directory passed by the caller.
func NewMockValidator(language, toolchain, projectDir string) *MockValidator {
	return &MockValidator{
		Language:   language,
		Toolchain:  toolchain,
		ProjectDir: projectDir,
	}
}

// mockStubHeader is the leading banner emitted into every generated mock file.
// It marks the file as an auto-generated stub so downstream tooling can detect
// and re-generate it without confusing it for hand-written code.
const mockStubHeader = "// Code generated by MockValidator; DO NOT EDIT.\n"

// ValidateInIsolation runs State-Grounded Mock-Based In-Isolation Validation
// for the supplied module against the listed dependency names. For every
// entry in deps a state-equivalent stub is generated (interface signature
// only — no behaviour), the module is exercised against the stubs in an
// isolated temp directory using the configured toolchain (via
// tools.RunProjectTests), and per-stub assertion results are recorded.
//
// Returned errors are reserved for unrecoverable failures (e.g. the temp
// directory cannot be created, the toolchain itself returns an internal
// error). Individual stub / test failures are recorded in the report's Errors
// slice and surfaced via report.Passed == false; they do not produce an error
// return so callers can aggregate across modules.
func (mv *MockValidator) ValidateInIsolation(ctx context.Context, module string, deps []string) (IsolationReport, error) {
	report := IsolationReport{Module: module}

	if strings.TrimSpace(module) == "" {
		return report, fmt.Errorf("mock validator: module name is empty")
	}

	// 1. Spin up an isolated working directory so parallel validations cannot
	//    collide on shared fixtures.
	isoDir, err := os.MkdirTemp("", "magharcm-iso-"+sanitizeForFilename(module)+"-")
	if err != nil {
		return report, fmt.Errorf("mock validator: create isolation dir: %w", err)
	}
	defer func() {
		if rmErr := os.RemoveAll(isoDir); rmErr != nil {
			logger.LogWarning("mock validator: failed to remove isolation dir %s: %v", isoDir, rmErr)
		}
	}()

	logger.LogAgent("MockValidator", "isolating module %q with %d deps in %s", module, len(deps), isoDir)

	// 2. Generate a state-equivalent stub for every dependency. Each stub is an
	//    interface signature only — no behaviour — so the module under test
	//    must drive correctness through its own assertions rather than via
	//    incidental side effects of the dependency.
	for _, dep := range deps {
		stubPath, stubErr := writeMockStub(isoDir, dep)
		if stubErr != nil {
			report.Errors = append(report.Errors, fmt.Sprintf("generate stub for %s: %v", dep, stubErr))
			continue
		}
		report.MocksGenerated = append(report.MocksGenerated, stubPath)
		report.StateAssertions = append(report.StateAssertions, fmt.Sprintf("stub[%s] signature-emitted", dep))
	}

	// 3. Run the module against the stubs via the project toolchain. An empty
	//    ProjectDir is coerced to "." so tools.RunProjectTests can resolve the
	//    language registry against the current working tree when the caller
	//    has not supplied one.
	projectDir := mv.ProjectDir
	if projectDir == "" {
		projectDir = "."
	}

	lang := mv.Language
	if lang == "" {
		lang = consts.LangRust
	}
	toolchain := mv.Toolchain
	if toolchain == "" {
		toolchain = consts.ToolchainCargo
	}

	testOut, runErr := tools.RunProjectTests(ctx, projectDir, lang, toolchain, module)
	if runErr != nil {
		// Internal / unrecoverable toolchain failure — surface as Go error
		// so the caller can decide whether to abort the pipeline.
		return report, fmt.Errorf("mock validator: run tests for %s: %w", module, runErr)
	}

	// 4. Aggregate per-stub assertions and the overall toolchain outcome.
	//    A stub assertion is recorded as passing ONLY when the corresponding
	//    mock file was successfully generated AND the toolchain run reported
	//    no failures attributable to that stub. We treat the toolchain's
	//    pass/fail verdict as the shared signal across all stubs (the stubs
	//    themselves are inert, so a failure is by construction a failure of
	//    the module against its declared interface surface).
	if !testOut.Success {
		for _, line := range testOut.Failures {
			report.Errors = append(report.Errors, fmt.Sprintf("module[%s] failure: %s", module, line))
		}
		if len(testOut.Failures) == 0 {
			report.Errors = append(report.Errors, fmt.Sprintf("module[%s] toolchain reported failure: %s", module, testOut.Message))
		}
	}

	// Every successfully generated stub contributes an assertion that the
	// module was executed against an interface-compatible replacement.
	for _, stub := range report.MocksGenerated {
		report.StateAssertions = append(report.StateAssertions, fmt.Sprintf("module[%s] executed against %s", module, filepath.Base(stub)))
	}

	report.Passed = testOut.Success && len(report.Errors) == 0

	if report.Passed {
		logger.LogValidation("mock validator: module %q passed isolation against %d stubs", module, len(report.MocksGenerated))
	} else {
		logger.LogWarning("mock validator: module %q failed isolation (%d errors)", module, len(report.Errors))
	}

	return report, nil
}

// writeMockStub writes a state-equivalent stub for the supplied dependency
// into the isolation directory. The stub is an interface signature only — no
// behaviour — so the module under test must drive correctness through its own
// assertions. The returned path is the absolute path of the written file.
//
// Dep names are sanitized into safe filenames; characters outside
// [A-Za-z0-9_.-] are replaced with underscores. The stub body is intentionally
// trivial: a Go-style interface declaration (the validator's primary target is
// the Go toolchain via tools.RunProjectTests, which inspects the working tree
// even when the actual build runs in another toolchain via the language
// registry). For non-Go targets the stub file is harmless fixture content that
// does not influence the toolchain's pass/fail verdict.
func writeMockStub(isoDir, dep string) (string, error) {
	if strings.TrimSpace(dep) == "" {
		return "", fmt.Errorf("empty dependency name")
	}
	safe := sanitizeForFilename(dep)
	stubPath := filepath.Join(isoDir, safe+".go")

	var b strings.Builder
	b.WriteString(mockStubHeader)
	b.WriteString("package mocks\n\n")
	fmt.Fprintf(&b, "// %s is a state-equivalent stub generated for in-isolation validation.\n", safe)
	fmt.Fprintf(&b, "type %s interface {\n", safe)
	fmt.Fprintf(&b, "\t// Signature-only surface; behaviour is intentionally absent.\n")
	fmt.Fprintf(&b, "\tNoOp() error\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// New%s returns a no-op stub implementation.\n", safe)
	fmt.Fprintf(&b, "func New%s() %s { return nil }\n", safe, safe)

	if err := os.WriteFile(stubPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write stub %s: %w", stubPath, err)
	}
	return stubPath, nil
}

// sanitizeForFilename collapses any character outside [A-Za-z0-9_.-] into an
// underscore so a dependency name can be turned into a safe filesystem path.
// An empty result falls back to "stub" to guarantee a usable filename.
func sanitizeForFilename(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9',
			r == '_', r == '.', r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "stub"
	}
	return b.String()
}
