package types

import "fmt"

// TranslationTask defines the input specification for the translation pipeline.
type TranslationTask struct {
	SourceDir  string `json:"source_dir"`
	TargetDir  string `json:"target_dir"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
	Prompt     string `json:"prompt,omitempty"`
}

// SourceProjectResearch represents the research document produced in phase 3.2.1.
type SourceProjectResearch struct {
	Overview           string   `json:"overview"`
	DirectoryStructure string   `json:"directory_structure"`
	StructsInterfaces  string   `json:"structs_and_interfaces"`
	DataModels         string   `json:"data_models"`
	ErrorHandling      string   `json:"error_handling"`
	Dependencies       []string `json:"dependencies"`
	RawDocument        string   `json:"raw_document"`
}

// ThirdPartyLibraryAnalysis represents the library analysis document produced in phase 3.2.2.
type ThirdPartyLibraryAnalysis struct {
	Libraries   []LibraryMapping `json:"libraries"`
	RawDocument string           `json:"raw_document"`
}

// LibraryMapping details how a source library maps to a target library.
type LibraryMapping struct {
	SourceLibrary   string `json:"source_library"`
	TargetLibrary   string `json:"target_library"`
	Overview        string `json:"overview"`
	Usage           string `json:"usage"`
	Recommendations string `json:"recommendations"`
}

// TargetProjectDesign represents the design document produced in phase 3.2.3.
type TargetProjectDesign struct {
	Overview                string   `json:"overview"`
	TranslationRequirements string   `json:"translation_requirements"`
	SourceFilesToTranslate  []string `json:"source_files_to_translate"`
	ModuleStructure         string   `json:"module_structure"`
	ErrorHandling           string   `json:"error_handling"`
	ThirdPartyLibraries     []string `json:"third_party_libraries"`
	RawDocument             string   `json:"raw_document"`
}

// AnalyzerOutput aggregates the three documents generated by the Analyzer Agent (§3.2).
type AnalyzerOutput struct {
	Research DocumentWrapper[SourceProjectResearch]     `json:"research"`
	Library  DocumentWrapper[ThirdPartyLibraryAnalysis] `json:"library"`
	Design   DocumentWrapper[TargetProjectDesign]       `json:"design"`
}

// DocumentWrapper keeps both structured data and markdown representation.
type DocumentWrapper[T any] struct {
	Data        T      `json:"data"`
	RawMarkdown string `json:"raw_markdown"`
}

// PlanStep represents a single step in Part A or Part B of the implementation plan.
type PlanStep struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	SourceFile  string `json:"source_file"`
	TargetFile  string `json:"target_file"`
	Type        string `json:"type"` // "source" or "test"
	Completed   bool   `json:"completed"`
}

// ImplementationPlan partitions translation tasks into Part A and Part B (§3.3.4).
type ImplementationPlan struct {
	Overview string     `json:"overview"`
	PartA    []PlanStep `json:"part_a"` // Source code translation
	PartB    []PlanStep `json:"part_b"` // Test code translation & validation
	RawPlan  string     `json:"raw_plan"`
}

// PlanningOutput aggregates fragment extraction, name mapping, skeleton files, and plan (§3.3).
type PlanningOutput struct {
	Fragments     []string          `json:"fragments"`      // file_name:fragment_name
	NameMapping   map[string]string `json:"name_mapping"`   // source_name -> target_name
	SkeletonFiles map[string]string `json:"skeleton_files"` // relative_path -> skeleton_content
	Plan          ImplementationPlan `json:"plan"`
}

// TranslatedProject holds the current translated files in the target project (§3.4).
type TranslatedProject struct {
	Files map[string]string `json:"files"` // relative_path -> code_content
}

// ValidationReport holds results from building and running tests on the target project (§3.5).
type ValidationReport struct {
	AllSuccess         bool     `json:"all_success"`
	CompilationSuccess bool     `json:"compilation_success"`
	TestPassRate       float64  `json:"test_pass_rate"`
	TotalTests         int      `json:"total_tests"`
	PassedTests        int      `json:"passed_tests"`
	FailedTests        int      `json:"failed_tests"`
	CompilationErrors  []string `json:"compilation_errors"`
	TestFailures       []string `json:"test_failures"`
	UncoveredFunctions []string `json:"uncovered_functions"`
	CoverageGapReport  string   `json:"coverage_gap_report"`
	Diagnostics        string   `json:"diagnostics"`
}

// HasUncoveredFunctions returns true if there are functions lacking test coverage (§3.5.2).
func (v *ValidationReport) HasUncoveredFunctions() bool {
	return len(v.UncoveredFunctions) > 0
}

// IsAllSuccess returns true if compilation succeeds and at least one test passes (>0% pass rate).
func (v *ValidationReport) IsAllSuccess() bool {
	return v.CompilationSuccess && v.PassedTests > 0 && len(v.CompilationErrors) == 0
}

// String provides a human-readable summary of the validation report.
func (v *ValidationReport) String() string {
	if v.IsAllSuccess() {
		return fmt.Sprintf("Validation SUCCESS: %d/%d tests passed (%.1f%% pass rate > 0%%)", v.PassedTests, v.TotalTests, v.TestPassRate)
	}
	return fmt.Sprintf("Validation INCOMPLETE: compilation=%v, passed=%d/%d, compile_errs=%d, test_fails=%d, uncovered=%d\nDiagnostics:\n%s",
		v.CompilationSuccess, v.PassedTests, v.TotalTests, len(v.CompilationErrors), len(v.TestFailures), len(v.UncoveredFunctions), v.Diagnostics)
}
// State is the shared context passed between Eino graph nodes.
type State struct {
	Task             TranslationTask    `json:"task"`
	AnalyzerOutput   AnalyzerOutput     `json:"analyzer_output"`
	PlanningOutput   PlanningOutput     `json:"planning_output"`
	TranslatedProject TranslatedProject `json:"translated_project"`
	ValidationReport ValidationReport   `json:"validation_report"`
	Iteration        int                `json:"iteration"`
	MaxIterations    int                `json:"max_iterations"`
	IsComplete       bool               `json:"is_complete"`
	Logs             []string           `json:"logs"`
	FinalSummary     string             `json:"final_summary"`
}

// Log records a state progress message.
func (s *State) Log(format string, args ...any) {
	msg := fmt.Sprintf(format, args...)
	s.Logs = append(s.Logs, msg)
}
